server:
  port: 8011

#微服务
dubbo:
  application:
    name: mall-order

  protocol:
    name: dubbo
    port: 20881

  #nacos注册中心
  registry:
    address: nacos://127.0.0.1:8851


#配置多个数据源
spring:
  shardingsphere:
    datasource:
      names: m1,m2
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/oms1?serverTimezone=GMT%2B8
        username: root
        password: 12345678

      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/oms2?serverTimezone=GMT%2B8
        username: root
        password: 12345678

    sharding:

      tables:
        #订单表
        torder:

          #订单id生成策略，雪花算法
          key-generator:
            column: order_id
            type: SNOWFLAKE
            props:
              worker:
                id: 1

          #真实表分布，分库，分表
          actual-data-nodes: m$->{1..2}.torder_$->{1..2}

          #inline分片策略
          database-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: m$->{((order_id%4+1).intdiv(3))+1}

          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: torder_$->{((order_id%4+1)%2)+1}
    #打印SQL
    props:
      sql:
        show:  true
